# Generated by Django 5.2.4 on 2025-07-15 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, choices=[('USA', 'Estados Unidos'), ('BRAZIL', 'Brasil'), ('CHILE', 'Chile'), ('ARGENTINA', 'Argentina'), ('MEXICO', 'México'), ('SPAIN', 'Espanha'), ('ITALY', 'Itália'), ('PORTUGAL', 'Portugal'), ('RUSSIA', 'Rússia'), ('SOUTH_KOREA', 'Coreia do Sul'), ('SOUTH_AFRICA', 'África do Sul'), ('SWEDEN', 'Suécia'), ('NORWAY', 'Noruega'), ('FINLAND', 'Finlândia'), ('DENMARK', 'Dinamarca'), ('NETHERLANDS', 'Países Baixos'), ('BELGIUM', 'Bélgica'), ('SWITZERLAND', 'Suíça'), ('UK', 'Reino Unido'), ('FRANCE', 'França'), ('GERMANY', 'Alemanha'), ('CANADA', 'Canadá'), ('AUSTRALIA', 'Austrália'), ('INDIA', 'Índia'), ('JAPAN', 'Japão'), ('CHINA', 'China'), ('OTHER', 'Outro'), ('NOT_SPECIFIED', 'Não Especificado')], max_length=100, null=True)),
            ],
        ),
    ]
